package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSensors<M extends BaseSensors<M>> extends Model<M> implements IBean,ISensors {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setIsBlock(java.lang.Boolean isBlock) {
		set("is_block", isBlock);
		return (M)this;
	}

	public java.lang.Boolean getIsBlock() {
		return get("is_block");
	}

	public M setSmsSend(java.lang.Boolean smsSend) {
		set("sms_send", smsSend);
		return (M)this;
	}

	public java.lang.Boolean getSmsSend() {
		return get("sms_send");
	}

	public M setPushDesktop(java.lang.Boolean pushDesktop) {
		set("push_desktop", pushDesktop);
		return (M)this;
	}

	public java.lang.Boolean getPushDesktop() {
		return get("push_desktop");
	}

	public M setAlarmTypeId(java.lang.Long alarmTypeId) {
		set("alarm_type_id", alarmTypeId);
		return (M)this;
	}

	public java.lang.Long getAlarmTypeId() {
		return getLong("alarm_type_id");
	}

	public M setAlarmLevel(java.lang.Integer alarmLevel) {
		set("alarm_level", alarmLevel);
		return (M)this;
	}

	public java.lang.Integer getAlarmLevel() {
		return getInt("alarm_level");
	}

	public M setGeoId(java.lang.Long geoId) {
		set("geo_id", geoId);
		return (M)this;
	}

	public java.lang.Long getGeoId() {
		return getLong("geo_id");
	}

	public M setPosX(java.lang.String posX) {
		set("pos_x", posX);
		return (M)this;
	}

	public java.lang.String getPosX() {
		return getStr("pos_x");
	}

	public M setPosY(java.lang.String posY) {
		set("pos_y", posY);
		return (M)this;
	}

	public java.lang.String getPosY() {
		return getStr("pos_y");
	}

	public M setLastTime(java.lang.Integer lastTime) {
		set("last_time", lastTime);
		return (M)this;
	}

	public java.lang.Integer getLastTime() {
		return getInt("last_time");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setSensorTypeId(java.lang.Long sensorTypeId) {
		set("sensor_type_id", sensorTypeId);
		return (M)this;
	}

	public java.lang.Long getSensorTypeId() {
		return getLong("sensor_type_id");
	}

	public M setDeviceId(java.lang.Long deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.Long getDeviceId() {
		return getLong("device_id");
	}

	public M setUpThresholdValue(java.lang.String upThresholdValue) {
		set("up_threshold_value", upThresholdValue);
		return (M)this;
	}

	public java.lang.String getUpThresholdValue() {
		return getStr("up_threshold_value");
	}

	public M setDownThresholdValue(java.lang.String downThresholdValue) {
		set("down_threshold_value", downThresholdValue);
		return (M)this;
	}

	public java.lang.String getDownThresholdValue() {
		return getStr("down_threshold_value");
	}

	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}

	public java.lang.String getValue() {
		return getStr("value");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setOnline(java.lang.Boolean online) {
		set("online", online);
		return (M)this;
	}

	public java.lang.Boolean getOnline() {
		return get("online");
	}

	public M setStatValue(java.lang.String statValue) {
		set("stat_value", statValue);
		return (M)this;
	}

	public java.lang.String getStatValue() {
		return getStr("stat_value");
	}

}
