package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEventLog<M extends BaseEventLog<M>> extends Model<M> implements IBean,IEventLog {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setSensorsId(java.lang.Long sensorsId) {
		set("sensors_id", sensorsId);
		return (M)this;
	}

	public java.lang.Long getSensorsId() {
		return getLong("sensors_id");
	}

	public M setDevicesId(java.lang.Long devicesId) {
		set("devices_id", devicesId);
		return (M)this;
	}

	public java.lang.Long getDevicesId() {
		return getLong("devices_id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setData(java.lang.String data) {
		set("data", data);
		return (M)this;
	}

	public java.lang.String getData() {
		return getStr("data");
	}

	public M setValue(java.lang.Double value) {
		set("value", value);
		return (M)this;
	}

	public java.lang.Double getValue() {
		return getDouble("value");
	}

	public M setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
		return (M)this;
	}

	public java.lang.Integer getAddTime() {
		return getInt("add_time");
	}

}
