package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAlarm<M extends BaseAlarm<M>> extends Model<M> implements IBean,IAlarm {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setType(java.lang.Long type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Long getType() {
		return getLong("type");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public M setCompanyId(java.lang.Long companyId) {
		set("company_id", companyId);
		return (M)this;
	}

	public java.lang.Long getCompanyId() {
		return getLong("company_id");
	}

	public M setGeoId(java.lang.Long geoId) {
		set("geo_id", geoId);
		return (M)this;
	}

	public java.lang.Long getGeoId() {
		return getLong("geo_id");
	}

	public M setDeviceId(java.lang.Long deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.Long getDeviceId() {
		return getLong("device_id");
	}

	public M setSensorId(java.lang.Long sensorId) {
		set("sensor_id", sensorId);
		return (M)this;
	}

	public java.lang.Long getSensorId() {
		return getLong("sensor_id");
	}

	public M setIsDeal(java.lang.Integer isDeal) {
		set("is_deal", isDeal);
		return (M)this;
	}

	public java.lang.Integer getIsDeal() {
		return getInt("is_deal");
	}

	public M setDealUserId(java.lang.Long dealUserId) {
		set("deal_user_id", dealUserId);
		return (M)this;
	}

	public java.lang.Long getDealUserId() {
		return getLong("deal_user_id");
	}

	public M setAlarmValue(java.lang.String alarmValue) {
		set("alarm_value", alarmValue);
		return (M)this;
	}

	public java.lang.String getAlarmValue() {
		return getStr("alarm_value");
	}

	public M setAddTime(java.lang.Long addTime) {
		set("add_time", addTime);
		return (M)this;
	}

	public java.lang.Long getAddTime() {
		return getLong("add_time");
	}

	public M setUpdateTime(java.lang.Long updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.lang.Long getUpdateTime() {
		return getLong("update_time");
	}

	public M setDealTime(java.lang.Long dealTime) {
		set("deal_time", dealTime);
		return (M)this;
	}

	public java.lang.Long getDealTime() {
		return getLong("deal_time");
	}

	public M setTimes(java.lang.Integer times) {
		set("times", times);
		return (M)this;
	}

	public java.lang.Integer getTimes() {
		return getInt("times");
	}

	public M setDetail(java.lang.String detail) {
		set("detail", detail);
		return (M)this;
	}

	public java.lang.String getDetail() {
		return getStr("detail");
	}

}
