package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePhoto<M extends BasePhoto<M>> extends Model<M> implements IBean,IPhoto {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setMd5(java.lang.String md5) {
		set("md5", md5);
		return (M)this;
	}

	public java.lang.String getMd5() {
		return getStr("md5");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public M setWidth(java.lang.Integer width) {
		set("width", width);
		return (M)this;
	}

	public java.lang.Integer getWidth() {
		return getInt("width");
	}

	public M setHeight(java.lang.Integer height) {
		set("height", height);
		return (M)this;
	}

	public java.lang.Integer getHeight() {
		return getInt("height");
	}

	public M setCdn(java.lang.String cdn) {
		set("cdn", cdn);
		return (M)this;
	}

	public java.lang.String getCdn() {
		return getStr("cdn");
	}

	public M setCreatedTime(java.lang.Integer createdTime) {
		set("created_time", createdTime);
		return (M)this;
	}

	public java.lang.Integer getCreatedTime() {
		return getInt("created_time");
	}

}
