package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCompanyGeo<M extends BaseCompanyGeo<M>> extends Model<M> implements IBean,ICompanyGeo {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	public M setPhotoId(java.lang.Long photoId) {
		set("photo_id", photoId);
		return (M)this;
	}

	public java.lang.Long getPhotoId() {
		return getLong("photo_id");
	}

	public M setPlanName(java.lang.String planName) {
		set("plan_name", planName);
		return (M)this;
	}

	public java.lang.String getPlanName() {
		return getStr("plan_name");
	}

	public M setPosX(java.lang.String posX) {
		set("pos_x", posX);
		return (M)this;
	}

	public java.lang.String getPosX() {
		return getStr("pos_x");
	}

	public M setPosY(java.lang.String posY) {
		set("pos_y", posY);
		return (M)this;
	}

	public java.lang.String getPosY() {
		return getStr("pos_y");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setAllName(java.lang.String allName) {
		set("all_name", allName);
		return (M)this;
	}

	public java.lang.String getAllName() {
		return getStr("all_name");
	}

	public M setChildrenIds(java.lang.String childrenIds) {
		set("children_ids", childrenIds);
		return (M)this;
	}

	public java.lang.String getChildrenIds() {
		return getStr("children_ids");
	}

}
