package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWebConfig<M extends BaseWebConfig<M>> extends Model<M> implements IBean,IWebConfig {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCompanyId(java.lang.Long companyId) {
		set("company_id", companyId);
		return (M)this;
	}

	public java.lang.Long getCompanyId() {
		return getLong("company_id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setVersion(java.lang.String version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.String getVersion() {
		return getStr("version");
	}

	public M setAlarmList(java.lang.String alarmList) {
		set("alarm_list", alarmList);
		return (M)this;
	}

	public java.lang.String getAlarmList() {
		return getStr("alarm_list");
	}

}
