package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserLog<M extends BaseUserLog<M>> extends Model<M> implements IBean,IUserLog {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}

	public java.lang.String getIp() {
		return getStr("ip");
	}

	public M setAction(java.lang.String action) {
		set("action", action);
		return (M)this;
	}

	public java.lang.String getAction() {
		return getStr("action");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setAddTime(java.lang.Long addTime) {
		set("add_time", addTime);
		return (M)this;
	}

	public java.lang.Long getAddTime() {
		return getLong("add_time");
	}

	public M setObj(java.lang.String obj) {
		set("obj", obj);
		return (M)this;
	}

	public java.lang.String getObj() {
		return getStr("obj");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
