package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeviceTypeInfo<M extends BaseDeviceTypeInfo<M>> extends Model<M> implements IBean,IDeviceTypeInfo {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setVersion(java.lang.Integer version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.Integer getVersion() {
		return getInt("version");
	}

	public M setTimeOut(java.lang.Integer timeOut) {
		set("time_out", timeOut);
		return (M)this;
	}

	public java.lang.Integer getTimeOut() {
		return getInt("time_out");
	}

}
