package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAlarmConfig<M extends BaseAlarmConfig<M>> extends Model<M> implements IBean,IAlarmConfig {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCompanyId(java.lang.Long companyId) {
		set("company_id", companyId);
		return (M)this;
	}

	public java.lang.Long getCompanyId() {
		return getLong("company_id");
	}

	public M setSms(java.lang.String sms) {
		set("sms", sms);
		return (M)this;
	}

	public java.lang.String getSms() {
		return getStr("sms");
	}

	public M setSmsUsersIds(java.lang.String smsUsersIds) {
		set("sms_users_ids", smsUsersIds);
		return (M)this;
	}

	public java.lang.String getSmsUsersIds() {
		return getStr("sms_users_ids");
	}

	public M setSmsUsers(java.lang.String smsUsers) {
		set("sms_users", smsUsers);
		return (M)this;
	}

	public java.lang.String getSmsUsers() {
		return getStr("sms_users");
	}

	public M setSmsIsMass(java.lang.Integer smsIsMass) {
		set("sms_is_mass", smsIsMass);
		return (M)this;
	}

	public java.lang.Integer getSmsIsMass() {
		return getInt("sms_is_mass");
	}

	public M setMailSubject(java.lang.String mailSubject) {
		set("mail_subject", mailSubject);
		return (M)this;
	}

	public java.lang.String getMailSubject() {
		return getStr("mail_subject");
	}

	public M setMail(java.lang.String mail) {
		set("mail", mail);
		return (M)this;
	}

	public java.lang.String getMail() {
		return getStr("mail");
	}

	public M setMailUsersIds(java.lang.String mailUsersIds) {
		set("mail_users_ids", mailUsersIds);
		return (M)this;
	}

	public java.lang.String getMailUsersIds() {
		return getStr("mail_users_ids");
	}

	public M setMailUsers(java.lang.String mailUsers) {
		set("mail_users", mailUsers);
		return (M)this;
	}

	public java.lang.String getMailUsers() {
		return getStr("mail_users");
	}

	public M setMailIsMass(java.lang.Integer mailIsMass) {
		set("mail_is_mass", mailIsMass);
		return (M)this;
	}

	public java.lang.Integer getMailIsMass() {
		return getInt("mail_is_mass");
	}

	public M setGeoId(java.lang.Integer geoId) {
		set("geo_id", geoId);
		return (M)this;
	}

	public java.lang.Integer getGeoId() {
		return getInt("geo_id");
	}

	public M setAlarmType(java.lang.Integer alarmType) {
		set("alarm_type", alarmType);
		return (M)this;
	}

	public java.lang.Integer getAlarmType() {
		return getInt("alarm_type");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public M setCreateTime(java.lang.Integer createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.lang.Integer getCreateTime() {
		return getInt("create_time");
	}

	public M setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.lang.Integer getUpdateTime() {
		return getInt("update_time");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

}
