package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDevicesLog<M extends BaseDevicesLog<M>> extends Model<M> implements IBean,IDevicesLog {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setDeviceId(java.lang.Long deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.Long getDeviceId() {
		return getLong("device_id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setValue(java.lang.Double value) {
		set("value", value);
		return (M)this;
	}

	public java.lang.Double getValue() {
		return getDouble("value");
	}

	public M setDetail(java.lang.String detail) {
		set("detail", detail);
		return (M)this;
	}

	public java.lang.String getDetail() {
		return getStr("detail");
	}

	public M setLastTime(java.lang.Integer lastTime) {
		set("last_time", lastTime);
		return (M)this;
	}

	public java.lang.Integer getLastTime() {
		return getInt("last_time");
	}

	public M setAlarmId(java.lang.Long alarmId) {
		set("alarm_id", alarmId);
		return (M)this;
	}

	public java.lang.Long getAlarmId() {
		return getLong("alarm_id");
	}

}
