package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserRole<M extends BaseUserRole<M>> extends Model<M> implements IBean,IUserRole {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setAddTime(java.lang.Long addTime) {
		set("add_time", addTime);
		return (M)this;
	}

	public java.lang.Long getAddTime() {
		return getLong("add_time");
	}

	public M setIsCommon(java.lang.Boolean isCommon) {
		set("is_common", isCommon);
		return (M)this;
	}

	public java.lang.Boolean getIsCommon() {
		return get("is_common");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setIsShow(java.lang.Boolean isShow) {
		set("is_show", isShow);
		return (M)this;
	}

	public java.lang.Boolean getIsShow() {
		return get("is_show");
	}

}
