package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCompanyInfor<M extends BaseCompanyInfor<M>> extends Model<M> implements IBean,ICompanyInfor {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setLocation(java.lang.String location) {
		set("location", location);
		return (M)this;
	}

	public java.lang.String getLocation() {
		return getStr("location");
	}

	public M setFireRoomPhone(java.lang.String fireRoomPhone) {
		set("fire_room_phone", fireRoomPhone);
		return (M)this;
	}

	public java.lang.String getFireRoomPhone() {
		return getStr("fire_room_phone");
	}

	public M setFireDutyPersonName(java.lang.String fireDutyPersonName) {
		set("fire_duty_person_name", fireDutyPersonName);
		return (M)this;
	}

	public java.lang.String getFireDutyPersonName() {
		return getStr("fire_duty_person_name");
	}

	public M setFireDutyPersonPhone(java.lang.String fireDutyPersonPhone) {
		set("fire_duty_person_phone", fireDutyPersonPhone);
		return (M)this;
	}

	public java.lang.String getFireDutyPersonPhone() {
		return getStr("fire_duty_person_phone");
	}

	public M setPlanName(java.lang.String planName) {
		set("plan_name", planName);
		return (M)this;
	}

	public java.lang.String getPlanName() {
		return getStr("plan_name");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.lang.Integer getUpdateTime() {
		return getInt("update_time");
	}

}
