package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStatValue<M extends BaseStatValue<M>> extends Model<M> implements IBean,IStatValue {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setDevicesId(java.lang.Long devicesId) {
		set("devices_id", devicesId);
		return (M)this;
	}

	public java.lang.Long getDevicesId() {
		return getLong("devices_id");
	}

	public M setSensorsId(java.lang.Long sensorsId) {
		set("sensors_id", sensorsId);
		return (M)this;
	}

	public java.lang.Long getSensorsId() {
		return getLong("sensors_id");
	}

	public M setDataList(java.lang.String dataList) {
		set("data_list", dataList);
		return (M)this;
	}

	public java.lang.String getDataList() {
		return getStr("data_list");
	}

	public M setDataAvg(java.lang.Double dataAvg) {
		set("data_avg", dataAvg);
		return (M)this;
	}

	public java.lang.Double getDataAvg() {
		return getDouble("data_avg");
	}

	public M setDataHour(java.lang.String dataHour) {
		set("data_hour", dataHour);
		return (M)this;
	}

	public java.lang.String getDataHour() {
		return getStr("data_hour");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}

	public java.util.Date getDate() {
		return get("date");
	}

}
