package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by SqlBuilder, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStatOnline<M extends BaseStatOnline<M>> extends Model<M> implements IBean,IStatOnline {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setDevicesId(java.lang.Long devicesId) {
		set("devices_id", devicesId);
		return (M)this;
	}

	public java.lang.Long getDevicesId() {
		return getLong("devices_id");
	}

	public M setOnlineList(java.lang.String onlineList) {
		set("online_list", onlineList);
		return (M)this;
	}

	public java.lang.String getOnlineList() {
		return getStr("online_list");
	}

	public M setOnlineHour(java.lang.String onlineHour) {
		set("online_hour", onlineHour);
		return (M)this;
	}

	public java.lang.String getOnlineHour() {
		return getStr("online_hour");
	}

	public M setOnlineTime(java.lang.Integer onlineTime) {
		set("online_time", onlineTime);
		return (M)this;
	}

	public java.lang.Integer getOnlineTime() {
		return getInt("online_time");
	}

	public M setNotOnlineTime(java.lang.Integer notOnlineTime) {
		set("not_online_time", notOnlineTime);
		return (M)this;
	}

	public java.lang.Integer getNotOnlineTime() {
		return getInt("not_online_time");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}

	public java.util.Date getDate() {
		return get("date");
	}

}
