package tpson.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tp_alarm", "id", Alarm.class);
		arp.addMapping("tp_alarm_config", "id", AlarmConfig.class);
		arp.addMapping("tp_alarm_type", "id", AlarmType.class);
		arp.addMapping("tp_company_geo", "id", CompanyGeo.class);
		arp.addMapping("tp_company_infor", "id", CompanyInfor.class);
		arp.addMapping("tp_device_type_info", "id", DeviceTypeInfo.class);
		arp.addMapping("tp_devices", "id", Devices.class);
		arp.addMapping("tp_devices_log", "id", DevicesLog.class);
		arp.addMapping("tp_event_log", "id", EventLog.class);
		arp.addMapping("tp_fire_room", "id", FireRoom.class);
		arp.addMapping("tp_photo", "id", Photo.class);
		arp.addMapping("tp_sensors", "id", Sensors.class);
		arp.addMapping("tp_sensors_log", "id", SensorsLog.class);
		arp.addMapping("tp_sensors_type", "id", SensorsType.class);
		arp.addMapping("tp_sms", "id", Sms.class);
		arp.addMapping("tp_stat_alarm", "id", StatAlarm.class);
		arp.addMapping("tp_stat_online", "id", StatOnline.class);
		arp.addMapping("tp_stat_value", "id", StatValue.class);
		arp.addMapping("tp_system_setting", "id", SystemSetting.class);
		arp.addMapping("tp_user", "id", User.class);
		arp.addMapping("tp_user_action", "id", UserAction.class);
		arp.addMapping("tp_user_action_group", "id", UserActionGroup.class);
		arp.addMapping("tp_user_log", "id", UserLog.class);
		arp.addMapping("tp_user_role", "id", UserRole.class);
		arp.addMapping("tp_user_role_action", "id", UserRoleAction.class);
		arp.addMapping("tp_web_config", "id", WebConfig.class);
	}
}

