package tpson.model;

import com.jfinal.model.MergeConfig;
import com.jfinal.model.MergeUtil;
import com.jfinal.model.iAutoBind;
import tpson.model.base.BaseAlarm;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Alarm extends BaseAlarm<Alarm> implements iAutoBind {
	public static final Alarm dao = new Alarm().dao();

	@Override
	public void bind(List<?> data, String columnName) {
		switch (columnName){
			case "deal_user_id":
				MergeUtil.merge(data, User.dao, columnName);
				break;
			case "alarm_value":
				MergeConfig config2 = new MergeConfig(columnName,"sms_users")
						.setColumns("sms","mail_subject");
				MergeUtil.merge(data, AlarmConfig.dao, config2);
				break;
			case "geo_id":
				MergeConfig config = new MergeConfig(columnName)
						.setAlias("name","geo_name")
						.setAlias("all_name", "geo_all_name")
						.setColumns("name","all_name","pos_x","pos_y","photo_id");

				MergeUtil.merge(data, CompanyGeo.dao, config);
				MergeUtil.merge(data, Photo.dao, "photo_id").removeColumn("geo_id2");
				break;
			case "type":
				MergeUtil.merge(data, AlarmType.dao, columnName);
				break;
			case "device_id":
				MergeUtil.merge(data, Devices.dao, columnName);
				break;
			case "sensor_id":
				MergeConfig sensorConfig = new MergeConfig(columnName)
						.setAlias("name","sensor_name")
						.setAlias("pos_x","sensor_pos_x")
						.setAlias("pos_y","sensor_pos_y")
						.setColumns("name","pos_x","pos_y");
				MergeUtil.merge(data, Sensors.dao, sensorConfig);
				break;
		}

	}
}
