package tpson.model;

import com.jfinal.model.SqlBuilder;
import tpson.model.base.BaseAlarmConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlarmConfig extends BaseAlarmConfig<AlarmConfig> {
	public static final AlarmConfig dao = new AlarmConfig().dao();

	public boolean addOrSave(AlarmConfig config){
		if (config.getId() != null){
			config.setCreateTime((int)(System.currentTimeMillis()/1000));
			config.setUpdateTime((int)(System.currentTimeMillis()/1000));
			return config.update();
		}else{
			config.setCreateTime((int)(System.currentTimeMillis()/1000));
			return config.save();
		}
	}
}
