package tpson.model;

import com.jfinal.kit.StrKit;
import com.jfinal.model.MergeConfig;
import com.jfinal.model.MergeUtil;
import com.jfinal.model.iAssociation;
import com.jfinal.model.iAutoBind;
import tpson.model.base.BaseCompanyGeo;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanyGeo extends BaseCompanyGeo<CompanyGeo> implements iAssociation,iAutoBind {

	public static final CompanyGeo dao = new CompanyGeo().dao();

	@Override
	public MergeConfig association(String fk) {
		fk = StrKit.isBlank(fk)?"geo_id":fk;
		return new MergeConfig(fk)
				.setAlias("name","geo_name")
				.setAlias("all_name", "geo_all_name")
				.setColumns("name","all_name");
	}

	@Override
	public void bind(List<?> data, String columnName) {
		switch (columnName){
			case "photo_id":
				MergeUtil.merge(data, Photo.dao,"photo_id");
				break;
		}
	}
}
