package tpson.model;

import tpson.model.base.BaseCompanyInfor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanyInfor extends BaseCompanyInfor<CompanyInfor> {
	public static final CompanyInfor dao = new CompanyInfor().dao();
}
