package tpson.model;

import com.jfinal.kit.StrKit;
import com.jfinal.model.MergeConfig;
import com.jfinal.model.iAssociation;
import tpson.model.base.BaseCompanyInfor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanyInfo extends BaseCompanyInfor<CompanyInfo> implements iAssociation {
	public static final CompanyInfo dao = new CompanyInfo().dao();

	@Override
	public MergeConfig association(String fk) {
		fk = StrKit.isBlank(fk)?"company_id":fk;
		return new MergeConfig(fk)
				.setAlias("name","company_name")
				.setColumns("name");
	}
}
