package tpson.model;

import tpson.model.base.BaseDeviceTypeInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceTypeInfo extends BaseDeviceTypeInfo<DeviceTypeInfo> {
	public static final DeviceTypeInfo dao = new DeviceTypeInfo().dao();
}
