package tpson.model;

import tpson.model.base.BaseDevicesLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DevicesLog extends BaseDevicesLog<DevicesLog> {
	public static final DevicesLog dao = new DevicesLog().dao();
}
