package tpson.model;

import com.jfinal.kit.StrKit;
import com.jfinal.model.*;
import tpson.model.base.BaseDevices;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Devices extends BaseDevices<Devices> implements iAssociation,iAutoBind {
	public static final Devices dao = new Devices().dao();

	@Override
	public MergeConfig association(String fk) {
		fk = StrKit.isBlank(fk)?"device_id":fk;
		return new MergeConfig(fk)
				.setAlias("name","device_name")
				.setColumns("name");
	}

	@Override
	public void bind(List<?> data, String columnName) {
		switch (columnName){
			case "fire_room_id":
				MergeUtil.merge(data, FireRoom.dao, columnName);
				break;
			case "geo_id":
				MergeUtil.merge(data, CompanyGeo.dao, columnName);
				break;
			case "type":
				Map<Object,Object> map = new HashMap<>();
				List<DeviceTypeInfo> deviceTypes = SqlBuilder.dao(DeviceTypeInfo.dao).select();
				deviceTypes.forEach(deviceType -> {
					map.put(deviceType.getType(),deviceType.getName());
				});
				MergeUtil.list(data).mergeMap("type","type_name",map);
				break;
		}
	}
}
