package tpson.model;

import com.jfinal.model.MergeUtil;
import com.jfinal.model.iAutoBind;
import tpson.model.base.BaseEventLog;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EventLog extends BaseEventLog<EventLog> implements iAutoBind {
	public static final EventLog dao = new EventLog().dao();

	@Override
	public void bind(List<?> data, String columnName) {
		switch (columnName){
			case "sensors_id":
				MergeUtil.merge(data, Sensors.dao, columnName);
				break;
			case "devices_id":
				MergeUtil.merge(data, Devices.dao, columnName);
				break;
			case "type":
				MergeUtil.list(data).mergeMap("type","type_name",logType);
				break;
		}
	}

	public static final Map<Object,Object> logType = new HashMap<Object,Object>(){{
		put(0,"未定义");
		put(1,"心跳");
		put(2,"设备常规信息");
		put(3,"设备故障信息");
		put(4,"设备报警信息");
		put(10,"压力传感器正常值");
		put(11,"压力传感器上限报警");
		put(12,"压力传感器下限报警");
		put(20,"液位传感器正常值");
		put(21,"液位传感器上限报警");
		put(22,"液位传感器下限报警");
		put(30,"温度传感器正常值");
		put(31,"温度传感器上限报警");
		put(32,"温度传感器下限报警");
		put(33,"温度传感器离线故障");
		put(40,"编码传感器常规信息");
		put(41,"编码传感器故障信息");
		put(42,"编码传感器报警信息");
		put(50,"剩余电流传感器正常值");
		put(51,"剩余电流传感器上限报警");
		put(60,"通用电流传感器正常值");
		put(61,"通用电流传感器上限报警");
		put(62,"通用电流传感器下限报警");
		put(70,"通用电压传感器正常值");
		put(71,"通用电压传感器上限报警");
		put(72,"通用电压传感器下限报警");
		put(80,"通用开关量传感器");
		put(81,"通用开关量传感器报警");
		put(82,"通用开关量传感器故障");
		put(90,"通用角度传感器");
		put(100,"通用模拟量传感器正常值");
		put(101,"通用模拟量传感器上限报警");
		put(102,"通用模拟量传感器下限报警");
	}};
}
