package tpson.model;

import com.jfinal.kit.StrKit;
import com.jfinal.model.MergeConfig;
import com.jfinal.model.iAssociation;
import tpson.model.base.BasePhoto;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Photo extends BasePhoto<Photo> implements iAssociation {
	public static final Photo dao = new Photo().dao();

	@Override
	public MergeConfig association(String fk) {
		fk = StrKit.isBlank(fk)?"photo_id":fk;
		return new MergeConfig(fk)
				.setAlias("url","img_url")
				.setColumns("url");
	}
}
