package tpson.model;

import com.jfinal.kit.StrKit;
import com.jfinal.model.MergeConfig;
import com.jfinal.model.MergeUtil;
import com.jfinal.model.iAssociation;
import com.jfinal.model.iAutoBind;
import tpson.model.base.BaseSensors;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sensors extends BaseSensors<Sensors> implements iAssociation,iAutoBind {
	public static final Sensors dao = new Sensors().dao();

	@Override
	public MergeConfig association(String fk) {
		fk = StrKit.isBlank(fk)?"sensor_id":fk;
		return new MergeConfig(fk)
				.setAlias("name","sensor_name")
				.setColumns("name","geo_id","up_threshold_value");
	}

	@Override
	public void bind(List<?> data, String columnName) {
		switch (columnName){
			case "device_id":
				MergeUtil.merge(data, Devices.dao, columnName);
				break;
			case "geo_id":
				MergeUtil.merge(data, CompanyGeo.dao, columnName);
				break;
			case "alarm_type_id":
				MergeUtil.merge(data, AlarmType.dao, columnName);
				break;
			case "sensor_type_id":
				MergeUtil.merge(data, SensorsType.dao, columnName);
				break;
		}
	}
}
