package tpson.model;

import tpson.model.base.BaseSensorsLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SensorsLog extends BaseSensorsLog<SensorsLog> {
	public static final SensorsLog dao = new SensorsLog().dao();
}
