package tpson.model;

import com.jfinal.kit.StrKit;
import com.jfinal.model.MergeConfig;
import com.jfinal.model.iAssociation;
import tpson.model.base.BaseSensorsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SensorsType extends BaseSensorsType<SensorsType> implements iAssociation {
	public static final SensorsType dao = new SensorsType().dao();

	@Override
	public MergeConfig association(String fk) {
		fk = StrKit.isBlank(fk)?"sensor_type_id":fk;
		return new MergeConfig(fk)
				.setAlias("name","sensor_type_name")
				.setColumns("name","has_value");
	}
}
