package tpson.model;

import tpson.model.base.BaseStatAlarm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatAlarm extends BaseStatAlarm<StatAlarm> {
	public static final StatAlarm dao = new StatAlarm().dao();
}
