package tpson.model;

import tpson.model.base.BaseStatOnline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatOnline extends BaseStatOnline<StatOnline> {
	public static final StatOnline dao = new StatOnline().dao();
}
