package tpson.model;

import tpson.model.base.BaseStatValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatValue extends BaseStatValue<StatValue> {
	public static final StatValue dao = new StatValue().dao();
}
