package tpson.model;

import tpson.model.base.BaseSystemSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemSetting extends BaseSystemSetting<SystemSetting> {
	public static final SystemSetting dao = new SystemSetting().dao();

}
