package tpson.model;

import tpson.model.base.BaseWebConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebConfig extends BaseWebConfig<WebConfig> {
	public static final WebConfig dao = new WebConfig().dao();
}
